name: core
description: Core package
version: 1.0.0
resolution: workspace
environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  fast_immutable_collections: ^11.2.0
  path: ^1.9.0
  signals_core: ^7.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
